import MainLayout from "./Components/MainLayout";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
           {children}
        </MainLayout>
      </body>
    </html>
  );
}
